### ISSUE TITLE
Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by hirokiosame** [mysticatea/vue-eslint-parser#11]
I believe a new version of this was released (yesterday?) that is breaking linting. Here is the error I get:

```
> eslint --ext js,vue src/components

Cannot read property 'message' of undefined
TypeError: Cannot read property 'message' of undefined
    at EventEmitter.VExpressionContainer[syntaxError!=null] (/Users/hiroki/Documents/Gits/orbit/node_modules/eslint-plugin-vue/lib/rules/no-parsing-error.js:27:39)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at NodeEventGenerator.applySelector (/Users/hiroki/Documents/Gits/orbit/node_modules/eslint/lib/util/node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors (/Users/hiroki/Documents/Gits/orbit/node_modules/eslint/lib/util/node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode (/Users/hiroki/Documents/Gits/orbit/node_modules/eslint/lib/util/node-event-generator.js:308:14)
    at traverse (/Users/hiroki/Documents/Gits/orbit/node_modules/vue-eslint-parser/index.js:183:13)
    at traverse (/Users/hiroki/Documents/Gits/orbit/node_modules/vue-eslint-parser/index.js:195:13)
    at traverse (/Users/hiroki/Documents/Gits/orbit/node_modules/vue-eslint-parser/index.js:190:21)
    at traverse (/Users/hiroki/Documents/Gits/orbit/node_modules/vue-eslint-parser/index.js:195:13)
```

Here are the relevant sections from my `npm list`:
```
├─┬ eslint@3.19.0
...
├─┬ eslint-plugin-vue@3.8.0
│ ├── requireindex@1.1.0
│ └─┬ vue-eslint-parser@1.1.0-8
│   └── eslint-scope@3.7.1
```

I do not get the error when I use 	`'plugin:vue/base'` instead of `'plugin:vue/recommended'` in my eslint config.

Let me know if you need me to provide more information.

**Comment by mysticatea** [comment]
Oh, I'm sorry.

Yes, `1.1.0-8` includes several breaking changes about AST. I thought that `pre-release` version is not upgraded automatically, but it looks wrong.

I will revert.

**Comment by mysticatea** [comment]
Reverted on v1.1.0-9

**Comment by hirokiosame** [comment]
Arigatz!
